#Application properties
server:
  port: 8080


#AWS properties
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: accessKey
      secretKey: secretKey+zc6Tk7M9

application:
  bucket:
    name: spring-boot-aws-storage

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
